spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/course}
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/course}
    user: root
    password: password
    connect-retries: 10

security:
  jwt:
    secret-key: MY_SECRET_KEY_AUTHORIZATION_BACKEND_COURSE_SERVICE_TOKEN_1234567
    access-token-expiration-days: 0
    access-token-expiration-hours: 1
    access-token-expiration-minutes: 0
    refresh-token-expiration-days: 7
    refresh-token-expiration-hours: 0
    refresh-token-expiration-minutes: 0

server:
  servlet:
    context-path: /backend-service
  port: 8000




